// 町の依頼。物語の進行で増え、同じ依頼を各難易度で遊べる。
const SIDE_QUESTS = (() => {
  const entries = [
    { id: 'q_harbor', title: '港の忘れもの', town: 'aquamist', need: 'act1', giver: '港の配達人', lv: 2, reward: 75, mapFrom: 'cove', desc: '朝の配達袋が、入り江に残された。道をふさぐ影を払い、雨が降る前に取り戻そう。', enemies: [{ kind: 'shade', lv: 2, n: 3 }], missions: [{ type: 'turns', n: 8 }, { type: 'hp', n: 60 }, { type: 'noItem' }], firstItems: { i_tea: 2 } },
    { id: 'q_lantern', title: '灯台に灯る約束', town: 'aquamist', need: 'act2', giver: '灯台守', lv: 4, reward: 130, mapFrom: 'cove', desc: '灯台までの浅瀬が、冷たい言葉で閉ざされた。グランと一緒に、帰る船の灯りを守ろう。', enemies: [{ kind: 'shade', lv: 4, n: 3 }, { kind: 'thorn', lv: 4 }], missions: [{ type: 'spiritUse', spirit: 'gran', n: 1 }, { type: 'noDown' }, { type: 'turns', n: 10 }], firstItems: { i_shard: 2 } },
    { id: 'q_tide', title: '潮騒の稽古', town: 'aquamist', need: 'act2', giver: 'グラン', lv: 5, reward: 170, mapFrom: 'cove', desc: '潮の満ち引きに心剣を合わせる稽古。グランの力を何度も借り、深碧の刃で穢れを切り分けよう。', enemies: [{ kind: 'shade', lv: 5, n: 4 }, { kind: 'thorn', lv: 5 }], missions: [{ type: 'spiritUse', spirit: 'gran', n: 2 }, { type: 'enchantKill', n: 1 }, { type: 'hp', n: 50 }], firstItems: { i_water: 1 } },
    { id: 'q_clock', title: '止まった小さな時計', town: 'aquamist', theme: { bg: 'cave_sky', preset: 'dusk', fx: 'motes:0.3', bgm: 'haruka' }, need: 'act2', giver: '港の時計屋の子', lv: 6, reward: 190, mapFrom: 'gran', desc: '時計の針に、言えなかった謝罪が絡みついている。透明の一閃で、重なった影をほどこう。', enemies: [{ kind: 'shade', lv: 6, n: 4 }, { kind: 'lead', lv: 5 }], missions: [{ type: 'flashMulti' }, { type: 'turns', n: 11 }, { type: 'hp', n: 50 }], firstItems: { i_powder: 2 } },
    { id: 'q_orchard', title: '苦い果実と手紙', town: 'aquamist', theme: { bg: 'forest', preset: 'dusk', fx: 'motes:0.4', bgm: 'forest' }, need: 'act3', giver: 'マリー', lv: 7, reward: 230, mapFrom: 'ivy', desc: '赤い果実の収穫を邪魔する影が現れた。怒りの色は傷つけず、果樹園のくすみだけを取り除こう。', enemies: [{ kind: 'boss', lv: 8 }, { kind: 'shade', lv: 7, n: 2 }, { kind: 'thorn', lv: 7, n: 2 }], missions: [{ type: 'bossLast' }, { type: 'noItem' }, { type: 'turns', n: 12 }], firstItems: { i_tea: 3 } },
    { id: 'q_thorns', title: '鳥たちの帰り道', town: 'aquamist', theme: { bg: 'forest', preset: 'dusk', fx: 'motes:0.4', bgm: 'forest' }, need: 'act4', giver: 'アイビー', lv: 9, reward: 280, mapFrom: 'ivy', desc: '若い蔦の先に、鳥たちが戻れずにいる。アイビーの力で影を縛り、安全な帰り道をつくろう。', enemies: [{ kind: 'thorn', lv: 9, n: 3 }, { kind: 'shade', lv: 9, n: 3 }], missions: [{ type: 'spiritUse', spirit: 'ivy', n: 2 }, { type: 'noDown' }, { type: 'dullMax', n: 60 }], firstItems: { i_ward: 2 } },
    { id: 'q_bloom', title: '花守りの試練', town: 'aquamist', theme: { bg: 'forest', preset: 'dusk', fx: 'motes:0.4', bgm: 'forest' }, need: 'act4', giver: '森の薬師', lv: 10, reward: 320, mapFrom: 'ivy', bondNeed: { spirit: 'ivy', n: 8 }, desc: '森の薬師が、アリアとアイビーの絆を確かめたいという。アイビーから覚えた力も、戦いの中で試してみよう。', enemies: [{ kind: 'thorn', lv: 10, n: 3 }, { kind: 'lead', lv: 10 }, { kind: 'shade', lv: 10, n: 2 }], missions: [{ type: 'skillUse', n: 1 }, { type: 'hp', n: 60 }, { type: 'turns', n: 12 }], firstItems: { i_water: 2 } },
    { id: 'q_bridge', title: '石の子たちの橋', town: 'stone', need: 'act5', giver: '石の子', lv: 12, reward: 390, mapFrom: 'spinel', desc: '村の橋に、新しい鉛の殻が積み重なった。スピネルと共に、割れ目を黄金の光でつなごう。', enemies: [{ kind: 'boss', lv: 13, armor: 2 }, { kind: 'lead', lv: 12, n: 3 }, { kind: 'shade', lv: 12, n: 2 }], missions: [{ type: 'spiritUse', spirit: 'spinel', n: 2 }, { type: 'bossLast' }, { type: 'noDown' }], firstItems: { i_shard: 2 } },
    { id: 'q_gold', title: '割れ目に宿る勇気', town: 'stone', need: 'act5', giver: 'スピネル', lv: 14, reward: 450, mapFrom: 'spinel', bondNeed: { spirit: 'spinel', n: 8 }, desc: '金継ぎの光をアリア自身の技にする試練。鉛の守りを貫き、傷の向こうへ進もう。', enemies: [{ kind: 'lead', lv: 14, n: 4, armor: 3 }, { kind: 'thorn', lv: 14, n: 2 }], missions: [{ type: 'skillUse', n: 2 }, { type: 'hp', n: 50 }, { type: 'turns', n: 13 }], firstItems: { i_ward: 3 } },
    { id: 'q_palette', title: '城下町の色祭り', town: 'rainbow', need: 'finale', giver: '祭りの絵師', lv: 16, reward: 520, mapFrom: 'king', desc: '祭りの広場から、絵の具の色が消えはじめた。パレット王と一緒に、七色の道を取り戻そう。', enemies: [{ kind: 'shade', lv: 16, n: 3 }, { kind: 'lead', lv: 16, n: 2 }, { kind: 'thorn', lv: 16, n: 2 }], missions: [{ type: 'spiritUse', spirit: 'king', n: 2 }, { type: 'rainbow', n: 45 }, { type: 'noDown' }], firstItems: { i_powder: 3 } },
    { id: 'q_stargarden', title: '星の庭の色合わせ', town: 'rainbow', need: 'finale', giver: 'パレット王', lv: 18, reward: 620, mapFrom: 'king', bondNeed: { spirit: 'king', n: 8 }, desc: '星の庭で、色と色の響き合いを学ぶ。王から覚えた力を使い、穢れに隠れた光を見つけよう。', enemies: [{ kind: 'boss', lv: 20, armor: 2 }, { kind: 'thorn', lv: 18, n: 3 }, { kind: 'lead', lv: 18, n: 2 }], missions: [{ type: 'skillUse', n: 2 }, { type: 'turns', n: 14 }, { type: 'hp', n: 60 }], firstItems: { i_water: 2 } },
    { id: 'q_echo', title: '四つの絆の残響', town: 'rainbow', need: 'done', giver: '旅の仲間たち', lv: 23, reward: 850, mapFrom: 'king', desc: '旅の終わりに残った、色の拒絶。精霊との絆から覚えた技をつなぎ、穢れの残響を静めよう。', enemies: [{ kind: 'boss', lv: 25, armor: 3 }, { kind: 'lead', lv: 23, n: 3 }, { kind: 'thorn', lv: 23, n: 3 }, { kind: 'shade', lv: 23, n: 2 }], missions: [{ type: 'skillUse', n: 3 }, { type: 'noDown' }, { type: 'rainbow', n: 55 }], firstItems: { i_shard: 3 } },
  ];
  return Object.fromEntries(entries.map(q => {
    const ref = BOARDS[q.mapFrom];
    if (q.bondNeed) q.missions = q.missions.map(m => m.type === 'skillUse' ? { ...m, spirit: q.bondNeed.spirit } : m);
    return [q.id, { unique: 'u_quest_' + q.id.slice(2), cols: q.lv >= 16 ? 11 : 9, rows: q.lv >= 16 ? 11 : 9, spStart: 6, act: 'サブクエスト',
      map: { ...ref.map, obsAmt: 0.04 }, hue: ref.hue, decor: ref.decor,
      theme: q.town === 'aquamist' ? { bg: 'rain', preset: 'dawn', fx: 'rain:0.15', bgm: 'haruka' }
        : q.town === 'grey' ? { bg: 'forest', preset: 'dusk', fx: 'motes:0.4', bgm: 'forest' }
        : q.town === 'stone' ? { bg: 'canyon', preset: 'dusk', fx: 'gold:0.4', bgm: 'forest' }
        : { bg: 'stars', preset: 'night', fx: 'stars:0.5', bgm: 'fate' }, ...q }];
  }));
})();
