const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http'),vm=require('node:vm');
const {chromium,webkit}=require('playwright');
const root=path.resolve(__dirname,'..');
test('Marii is rescued in mandatory chapter four and her travel knowledge connects the remaining main story',async()=>{
 const c=vm.createContext({localStorage:{getItem:()=>null}});for(const f of ['progression','story','quests','restoration-content','guardian-content','guardian-combat'])vm.runInContext(await fs.readFile(path.join(root,'js',f+'.js'),'utf8'),c);vm.runInContext((await fs.readFile(path.join(root,'js/world.js'),'utf8')).split('const World =')[0],c);for(const f of ['fury','mari-return'])vm.runInContext(await fs.readFile(path.join(root,'js',f+'.js'),'utf8'),c);
 const r=JSON.parse(vm.runInContext(`JSON.stringify({scripts:SCRIPT,skills:Progression.skills.filter(s=>s.spirit==='mari'),before:Progression.companions(['done']),after:Progression.companions(['done','maribond']),boss:BOARDS.mr_cocoon,path:BOARDS.gp_cocoon})`,c));
 const s=r.scripts.restore4;assert(s.indexOf('@board gp_cocoon')<s.indexOf('@board mr_cocoon'));assert(s.indexOf('@board mr_cocoon')<s.indexOf('@maribond'));assert(s.indexOf('@maribond')<s.indexOf('@board restore4'));assert(s.indexOf('@board restore4')<s.indexOf('@restore 4'));assert(!s.includes('@sideend'));
 assert(r.scripts.restore3.includes('灰黄色の羽根'));assert(r.scripts.restore5.includes('あなたの言葉で聞かせて'));assert(r.scripts.restore6.includes('ネリのお母さん'));assert(r.scripts.restore7.includes('時計師'));assert(r.scripts.restore8.includes('王妃から聞いた窓の歌'));assert(r.scripts.restored.includes('谷の修理師'));assert(!Object.values(r.scripts).some(s=>s.includes('プリズム王国')));
 assert(!r.before.includes('mari'));assert(r.after.includes('mari'));for(const route of ['enchant','summon'])assert.deepEqual(r.skills.filter(s=>s.route===route).map(s=>s.at),[8,20,40]);assert(r.boss.postgame&&r.path.companion);assert.equal(r.boss.difficultyFrom,'restore4');
});
let server,base,browsers;
const hook=`__mariQA:{ready:()=>running&&!busy&&!paused&&!over,
 state:()=>({cfg:cfg.id,spirits:cfg.spirits,turn,sp,units:units.map(u=>({id:u.id,kind:u.kind,wind:u.windTurns||0,mov:effMov(u),enchant:u.enchant,dead:u.dead}))}),
 finish(){units.filter(u=>u.side==='enemy').forEach(u=>u.dead=true);cells.filter(c=>c.beacon).forEach(c=>c.beaconOn=true);stats.purify=3;cells.forEach(c=>paint(c,'rainbow'));win();},
 fixture(){Object.assign(ariaU(),{r:5,c:4,hp:100,mhp:100});const e=units.find(u=>u.side==='enemy');Object.assign(e,{r:1,c:1,hp:10000,mhp:10000,atk:1});sp=12;refreshHud();select(ariaU(),true);},
 wind(){ariaU().windTurns=2;ariaU().windFrom=turn;refreshHud();},
 next(){return runTask(playerPhase());},
 summon(){return runTask(summon(ariaU(),'mari',cells.find(c=>c.walk&&!unitAt(c)&&dist(c,ariaU())<=2)));},
}, `;
before(async()=>{
 server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://local'),file=path.resolve(root,'.'+decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(!file.startsWith(root+path.sep)||file.includes(path.sep+'.'))throw Error();res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.mp3':'audio/mpeg'})[path.extname(file)]||'application/octet-stream'});res.end(await fs.readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/`;browsers={chromium:await chromium.launch(),webkit:await webkit.launch()};
});
after(async()=>{for(const b of Object.values(browsers||{}))await b.close();if(server)await new Promise(r=>server.close(r));});
async function session(engine,run,{joined=false,progress=3,checkpoint={chapter:'restore4',idx:0,map:true,at:12345}}={}){
 const ctx=await browsers[engine].newContext({viewport:{width:390,height:844},hasTouch:true}),page=await ctx.newPage(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)errors.push(r.status()+' '+r.url());});
 await ctx.addInitScript(({joined,progress,checkpoint})=>{if(localStorage.cr_mari_seed)return;localStorage.cr_mari_seed='1';localStorage.cr_unlocked=JSON.stringify(['prologue','act1','act2','act3','act4','act5','finale','epilogue','done',...Array.from({length:8},(_,i)=>'restore'+(i+1)),...(joined?['maribond']:[])]);localStorage.cr_settings=JSON.stringify({reduceMotion:true,textSize:'normal'});localStorage.cr_speed='0';localStorage.cr_save=JSON.stringify(checkpoint);localStorage.cr_party=JSON.stringify({aria:{lv:26,exp:0},chrome:{lv:26,exp:0},postgame:{started:true,progress},gold:400,spirits:{mari:{lv:26,bond:80,training:{enchant:40,summon:40}}}});},{joined,progress,checkpoint});
 const source=await fs.readFile(path.join(root,'js/board.js'),'utf8');await page.route('**/js/board.js*',r=>r.fulfill({contentType:'application/javascript',body:source.replace('    start, enterPhase1, help, stop,',hook+'    start, enterPhase1, help, stop,')}));await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));
 try{await page.goto(base+'#world',{waitUntil:'networkidle'});await page.locator('#gate').click();await page.locator('#world').waitFor({state:'visible'});try{await run(page);}catch(e){e.message+='; errors: '+JSON.stringify(errors);await page.screenshot({path:'/tmp/cr-mari-failure-'+engine+'.png'});throw e;}assert.deepEqual(errors,[]);}finally{await ctx.close();}
}
const ready=p=>p.waitForFunction(()=>Board.__mariQA.ready(),null,{timeout:20000}),state=p=>p.evaluate(()=>Board.__mariQA.state());
async function advance(p,predicate){for(let i=0;i<300;i++){if(await p.evaluate(predicate))return;if(await p.locator('#chapterCard:not(.hidden):not(.out)').count())await p.locator('#chapterCard').click();else if(await p.locator('#textbox:not(.hidden),#centerText.show').count()){await p.evaluate(()=>document.activeElement?.blur());await p.keyboard.press('Enter');}await p.waitForTimeout(60);}assert.fail('Story stopped: '+await p.locator('#text').textContent());}
async function finish(p){await p.evaluate(()=>Board.__mariQA.finish());await p.locator('#resNext').waitFor();await p.locator('#resNext').click();}
async function rescue(p){await p.evaluate(()=>{Panel.close();const lines=SCRIPT.restore4.split('\n').map(l=>l.trim()).filter(Boolean);Engine.play('restore4',lines.indexOf('@board gp_cocoon'));});await ready(p);assert.equal((await state(p)).cfg,'gp_cocoon');await finish(p);await advance(p,()=>Board.running&&Board.__mariQA.state().cfg==='mr_cocoon');await ready(p);}
for(const engine of ['chromium','webkit']){
 test(`${engine}: core rescue joins Marii before the record institute and resumes through a portable save`,async()=>{
  await session(engine,async p=>{
   assert(!await p.evaluate(()=>Restoration.canBegin('restore5')));await p.evaluate(()=>SkillForge.open());assert.equal(await p.locator('[data-forge-spirit=mari]').count(),0);await p.evaluate(()=>Panel.close());await rescue(p);assert(!await p.evaluate(()=>MariReturn.joined()));assert(!(await state(p)).spirits.includes('mari'));
   const portable=await p.evaluate(()=>SaveData.exportText());assert(await p.evaluate(t=>SaveData.importText(t).ok,portable));await p.reload({waitUntil:'networkidle'});await p.locator('#gate').click();await p.evaluate(()=>{World.close();Engine.cont();});await ready(p);assert.equal((await state(p)).cfg,'mr_cocoon');await finish(p);
   await advance(p,()=>Board.running&&Board.__mariQA.state().cfg==='restore4');await ready(p);assert(await p.evaluate(()=>MariReturn.joined()));assert((await state(p)).spirits.includes('mari'));await p.screenshot({path:`/tmp/cr-mari-${engine}-joined.png`});await finish(p);await advance(p,()=>World.isOpen&&Board.party.postgame.progress===4);assert.equal(await p.evaluate(()=>Engine.load().chapter),'restore5');assert(await p.evaluate(()=>Restoration.canBegin('restore5')));
   await p.evaluate(()=>SkillForge.open({spirit:'mari'}));assert.equal(await p.locator('[data-forge-spirit=mari]').count(),1);assert.equal(await p.locator('.sf-node').count(),3);await p.locator('[data-forge-route=summon]').click();assert.equal(await p.locator('.sf-node').count(),3);await p.screenshot({path:`/tmp/cr-mari-${engine}-forge.png`});const saved=await p.evaluate(()=>SaveData.exportText());assert(await p.evaluate(t=>SaveData.importText(t).ok,saved));assert(await p.evaluate(()=>MariReturn.joined()));
  });
 });
 test(`${engine}: older completed chapters recover Marii without losing the main bookmark or restoration progress`,async()=>{
  await session(engine,async p=>{
   await p.locator('[data-w=restoration]').click();assert.match(await p.locator('.pn-title').textContent(),/クリスタリア/);assert.match(await p.locator('.re-next').first().textContent(),/マリー/);await p.locator('[data-re-story-diff=hard]').click();assert.equal(await p.evaluate(()=>Board.party.stageDifficulty.restore4),'hard');await rescue(p);const bookmark=await p.evaluate(()=>Engine.load().returnStory);assert.equal(bookmark.chapter,'restore7');assert.equal(bookmark.at,67890);const portable=await p.evaluate(()=>SaveData.exportText());assert(await p.evaluate(t=>SaveData.importText(t).ok,portable));await finish(p);await advance(p,()=>Board.running&&Board.__mariQA.state().cfg==='restore4');await ready(p);await finish(p);await advance(p,()=>World.isOpen&&Engine.load().chapter==='restore7');assert.equal(await p.evaluate(()=>Board.party.postgame.progress),6);assert.equal(await p.evaluate(()=>Engine.load().at),67890);assert(await p.evaluate(()=>MariReturn.joined()));assert.equal(await p.evaluate(()=>Engine.load().returnStory),undefined);
  },{progress:6,checkpoint:{chapter:'restore7',idx:0,map:true,at:67890}});
 });
 test(`${engine}: Marii enchant and summon share temporary wind without stacking or permanently changing movement`,async()=>{
  await session(engine,async p=>{
   const start=()=>p.evaluate(()=>{World.close();Board.start({...BOARDS.cove,intro:null,tutorial:null,beats:[],spirits:[],spStart:12,map:{low:['land_flat'],mid:['land_flat'],high:['land_flat'],hills:0,obsAmt:0,waterAmt:0},enemies:[{kind:'shade',lv:1}]});});await start();await ready(p);await p.evaluate(()=>Board.__mariQA.fixture());await p.locator('#actHere').click();await p.locator('[data-k=spirit]').click();await p.locator('[data-k=enchant][data-a=mari]').click();await ready(p);assert.equal((await state(p)).units.find(u=>u.kind==='aria').mov,5);assert.equal((await state(p)).sp,9);await p.evaluate(()=>Board.__mariQA.wind());assert.equal((await state(p)).units.find(u=>u.kind==='aria').mov,5);for(let i=0;i<3;i++){await p.evaluate(()=>Board.__mariQA.next());await ready(p);}assert.equal((await state(p)).units.find(u=>u.kind==='aria').mov,4);
   await start();await ready(p);await p.evaluate(()=>Board.__mariQA.fixture());await p.evaluate(()=>Board.__mariQA.summon());await ready(p);assert(await p.evaluate(()=>GameArt.available('mari')));assert.equal((await state(p)).units.find(u=>u.kind==='aria').mov,5);for(let i=0;i<2;i++){await p.evaluate(()=>Board.__mariQA.next());await ready(p);}assert.equal((await state(p)).units.find(u=>u.kind==='aria').mov,4);
  },{joined:true,progress:4,checkpoint:{chapter:'restore5',idx:0,map:true}});
 });
}
